python paco_imagenet.py \
    --arch resnet50 \
    --dataset imagenet \
    --data /home/sharedir/research/ImageNet/ \
    --alpha 0.05 \
    --beta 1.0 \
    --wd 1e-4 \
    --gamma 1.0 \
    --mark paco_r50_fullImageNet \
    --lr 0.04 \
    -b 256 \
    --moco-t 0.2 \
    --aug randcls_sim \
    --epochs 400
